### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by DickvdBrink**
Work in progress;
- [x] Add references automatically
- [ ] Test on windows
- [ ] Publish on npm

### CODE REVIEW

**Comment by kbagga** [comment]
Unfortunately not yet working on windows 8/8.1 :(

**Comment by DickvdBrink** [comment]
Yeah i know, not finished yet but i'm on vacation.
I think I'm almost done with it though.. Hopefully I have some time again soon!

**Comment by TestVTeam** [comment]
Okay, will wait for it.

Thanks..

**Comment by DickvdBrink** [comment]
I added some commits, seems to be working on my machine! :) Requires some more testing though but looks good.

Edit: if someone is willing to try, it is `window.openDatabase` now instead of `window.WebSql.openDatabase` because I merged with master :)

**Pull request closed without merging**
